### ISSUE TITLE
CPU vs WASM

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [bminixhofer/tractjs#28]
In tfjs and ONNX.js, you can set the backend to webgl, wasm or cpu. I saw that gpu is not supported with tractjs, so webgl is not an option, but I don't see a place where we can choose between wasm or cpu. Is there such a thing or the backend is always wasm?
Thanks

**Comment by bminixhofer** [comment]
Hi, the backend is always WebAssembly. There is no reason to have anything such as "CPU" in addition to WASM because WASM runs on the CPU anyway, and tractjs is just a wrapper around tract, so having a Javascript backend would not make sense. 

I believe the CPU backends of tfjs and ONNX.js use Javascript, so they should be significantly slower than tractjs.

**Comment by RaphaelRoyerRivard** [comment]
Thank you for the clarification
